# fly.toml app configuration file generated for idol-planner on 2025-02-20T23:53:18+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'idol-planner'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 8080
  path = '/metrics'
  https = false
